import type { Metadata } from "next";
import "./globals.css";
import WalletProvider from "@/wagmi/walletProvider";
import SmartAccountClientProvider from "@/alchemy/SmartAccountClientProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<WalletProvider>
					<SmartAccountClientProvider>
						{children}
					</SmartAccountClientProvider>
				</WalletProvider>
			</body>
		</html>
	);
}
